### ISSUE TITLE
Use v2 notification API endpoint

### ISSUE THREAD

**Issue by aleph7** [bitrise-io/steps-hipchat#8]
Currently messages don't create a notification and don't support HTML. The step should use the v2 API and the notification endpoint: https://www.hipchat.com/docs/apiv2/method/send_room_notification

**Comment by viktorbenei** [comment]
Thanks for the report, we'll try to make some time for this early next year. If you would have time to make the required changes, we're always open to accept Pull Requests to our steps :)

**Comment by godrei** [comment]
Hi @aleph7 ,

we will share a new step with the v2 API, since it needs other access token then the v1 API. 

Just sharing a new version of this step (with the new API) would break every workflow, thats why we decided to create a new step.

However this step also will got a new version with some updates. I will notify you, when the v2 version is ready.

**Comment by godrei** [comment]
@aleph7 , sorry for my late response the Hipchat V2 step (`Send HipChat room notification`) will be available in the steplib soon (~20 min).

Thanks for the issue!
